version: '3.8'
services:
  postgres:
    image: postgres:15.0-alpine
    mem_limit: 128M
    volumes:
      - ./init-postgres/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  api:
    build:
      context: .
    links:
      - postgres
    environment:
      POSTGRES_URL: postgres://accounts:accounts-password@postgres:5432/accounts_db?sslmode=disable

  tests:
    build:
      context: .
      target: tests
    # Mount this volume to support local testing.
    # volumes:
    #   - .:/app/
    links:
      - postgres
    environment:
      POSTGRES_URL: postgres://accounts:accounts-password@postgres:5432/accounts_db?sslmode=disable
